//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudContainer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagsCloudContainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] en_us_aff {
            get {
                object obj = ResourceManager.GetObject("en_us_aff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 62118
        ///0/nm
        ///1/n1
        ///2/nm
        ///3/nm
        ///4/nm
        ///5/nm
        ///6/nm
        ///7/nm
        ///8/nm
        ///9/nm
        ///0th/pt
        ///1st/p
        ///1th/tc
        ///2nd/p
        ///2th/tc
        ///3rd/p
        ///3th/tc
        ///4th/pt
        ///5th/pt
        ///6th/pt
        ///7th/pt
        ///8th/pt
        ///9th/pt
        ///a
        ///A
        ///AA
        ///AAA
        ///Aachen/M
        ///aardvark/SM
        ///Aaren/M
        ///Aarhus/M
        ///Aarika/M
        ///Aaron/M
        ///AB
        ///aback
        ///abacus/SM
        ///abaft
        ///Abagael/M
        ///Abagail/M
        ///abalone/SM
        ///abandoner/M
        ///abandon/LGDRS
        ///abandonment/SM
        ///abase/LGDSR
        ///abasement/S
        ///abaser/M
        ///abashed/UY
        ///abashment/MS
        ///abash/SDLG
        ///abate/DSRLG
        ///abated/U
        ///abatement/MS
        ///abater/M
        ///abattoir/SM
        ///Abba/M
        ///Abbe/M
        ///abbй/S
        ///abbess/SM
        ///Abbey/M
        ///abbey/MS
        ///Abbie/M
        ///Abbi/M
        ///Abbot/M
        ///abbot/MS
        ///Ab [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_us_dic {
            get {
                return ResourceManager.GetString("en_us_dic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aboard
        ///about
        ///above
        ///absent
        ///across
        ///cross
        ///after
        ///against
        ///along
        ///alongside
        ///amid
        ///amidst
        ///among
        ///amongst
        ///apropos
        ///apud
        ///around
        ///as
        ///astride
        ///at
        ///atop
        ///ontop
        ///bar
        ///before
        ///afore
        ///behind
        ///ahind
        ///below
        ///beneath
        ///beside
        ///besides
        ///between	
        ///beyond
        ///but
        ///by
        ///circa
        ///come
        ///despite
        ///down
        ///during
        ///except
        ///for
        ///from
        ///in
        ///inside
        ///into
        ///less
        ///like
        ///minus
        ///near
        ///of
        ///off
        ///on
        ///onto
        ///opposite
        ///out
        ///outside
        ///over
        ///past
        ///per
        ///plus
        ///short
        ///since
        ///than
        ///through
        ///throughout
        ///till
        ///to
        ///toward, towards
        ///under
        ///underneath
        ///unli [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string listOfPrepositions {
            get {
                return ResourceManager.GetString("listOfPrepositions", resourceCulture);
            }
        }
    }
}
