//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudPainterApplication.Properties
{


    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    public sealed partial class AppSettings : global::System.Configuration.ApplicationSettingsBase, IAppSettings
    {

        private static AppSettings defaultInstance = ((AppSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new AppSettings())));

        public static AppSettings Default
        {
            get
            {
                return defaultInstance;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data\\BoringWords.txt")]
        public string BoringTextFilePath
        {
            get
            {
                return ((string)(this["boringTextFilePath"]));
            }
            set
            {
                this["boringTextFilePath"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public int ImageWidth
        {
            get
            {
                return ((int)(this["imageWidth"]));
            }
            set
            {
                this["imageWidth"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public int ImageHeight
        {
            get
            {
                return ((int)(this["imageHeight"]));
            }
            set
            {
                this["imageHeight"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int TagFontSize
        {
            get
            {
                return ((int)(this["tagFontSize"]));
            }
            set
            {
                this["tagFontSize"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Arial")]
        public string TagFontName
        {
            get
            {
                return ((string)(this["tagFontName"]));
            }
            set
            {
                this["tagFontName"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.1")]
        public double PointerStep
        {
            get
            {
                return ((double)(this["pointerStep"]));
            }
            set
            {
                this["pointerStep"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double PointerRadiusConst
        {
            get
            {
                return ((double)(this["pointerRadiusConst"]));
            }
            set
            {
                this["pointerRadiusConst"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double PointerAngleConst
        {
            get
            {
                return ((double)(this["pointerAngleConst"]));
            }
            set
            {
                this["pointerAngleConst"] = value;
            }
        }
    }
}
