//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TagsCloudContainer.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TagsCloudContainer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на к
        ///в
        ///на
        ///с
        ///про
        ///о
        ///за
        ///как
        ///и
        ///что
        ///не
        ///за
        ///ни
        ///нет
        ///а
        ///у
        ///я
        ///он
        ///она
        ///оно
        ///они
        ///вы
        ///мы
        ///из
        ///проститутка
        ///их
        ///чем
        ///весь
        ///его
        ///от
        ///по
        ///ли
        ///но
        ///до
        ///тот
        ///ты.
        /// </summary>
        internal static string blacklist {
            get {
                return ResourceManager.GetString("blacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] cloud {
            get {
                object obj = ResourceManager.GetObject("cloud", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] ru_aff {
            get {
                object obj = ResourceManager.GetObject("ru_aff", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 173975
        ///а
        ///аба/IIIhIw
        ///абажур/IIIiIhIk
        ///абажурный/CCCDCO
        ///абажурчик/IIIiIhIk
        ///абаз/IIIiIhIk
        ///абазин/IIIiIh
        ///абазинец/IKIw
        ///абазинка/IIIhIe
        ///абазинский/CCZZ
        ///абазия/IIIw
        ///абак/IIIiIhIk
        ///абака/IIIhIw
        ///Абакан/IIIiIhIk
        ///абаканский/CCZZ
        ///аббат/IIIiIhIk
        ///аббатиса/IIIhIe
        ///аббатский/CCZZ
        ///аббатство/IIIw
        ///аббревиатура/IIIhIw
        ///аббревиатурный/CCCDCO
        ///аббревиация/IIIw
        ///абвер/IIIiIhIk
        ///абверовский/CCZZ
        ///абдикация/IIIw
        ///абдомен/IIIiIhIk
        ///абдоминальный/CCCDCO
        ///абдуктор/IIIiIhIk
        ///абдукторный/CCCDCO
        ///абдукция/IIIw
        ///Абдул/II [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string ru_dic {
            get {
                return ResourceManager.GetString("ru_dic", resourceCulture);
            }
        }
    }
}
